version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "StrongPassword123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  api:
    image: jimmydoc1/apipersonas:latest
    container_name: apipersonas
    depends_on:
      - sqlserver
    environment:
      ConnectionStrings__DefaultConnection: >
        Server=sqlserver;
        Database=PersonaDb;
        User Id=sa;
        Password=StrongPassword123!;
        TrustServerCertificate=True
    ports:
      - "8081:8080"
